name: flutter_project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0

dev_dependencies:
  build_runner:
  generator_package:
    path: ../generator_package
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
